export const fruitEmojis: { [key: string]: string } = {
  Persimmon: "🍊",
  Strawberry: "🍓",
  Banana: "🍌",
  Tomato: "🍅",
  Pear: "🍐",
  Durian: "🥥",
  Blackberry: "🍇",
  Lingonberry: "🍇",
  Kiwi: "🥝",
  Lychee: "🍈",
  Pineapple: "🍍",
  Fig: "🍑",
  Gooseberry: "🍇",
  Passionfruit: "🍉",
  Plum: "🍑",
  Orange: "🍊",
  GreenApple: "🍏",
  Raspberry: "🍇",
  Watermelon: "🍉",
  Lemon: "🍋",
  Mango: "🥭",
  Blueberry: "🫐",
  Apple: "🍎",
  Guava: "🍇",
  Apricot: "🍑",
  Melon: "🍈",
  Tangerine: "🍊",
  Pitahaya: "🐉",
  Lime: "🍋",
  Pomegranate: "🍎",
  Dragonfruit: "🐉",
  Grape: "🍇",
  Morus: "🍇",
  Feijoa: "🍈",
  Avocado: "🥑",
  Kiwifruit: "🥝",
  Cranberry: "🍇",
  Cherry: "🍒",
  Peach: "🍑",
  Jackfruit: "🍈",
  "Horned Melon": "🍈",
  Hazelnut: "🥜",
  Pomelo: "🍊",
  Mangosteen: "🍈",
  Pumpkin: "🎃",
  "Japanese Persimmon": "🍊",
  Papaya: "🍍",
  Annona: "🍈",
  "Ceylon Gooseberry": "🍇",
};

export const DEFAULT_FRUIT_EMOJI = "🍇"; // Grape emoji as a default
